[platformio]
default_envs = supermini
boards_dir = boards
src_dir = src
include_dir = include
lib_dir = lib
test_dir = test

[env]
platform = nordicnrf52
board = nicenano
framework = arduino
board_build.variants_dir = boards
monitor_speed = 115200
upload_protocol = nrfutil
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.14
check_tool = cppcheck
check_skip_packages = yes
check_src_filters =
    +<src/>
    +<include/>
check_flags =
    cppcheck: --enable=warning,style,performance,portability
    cppcheck: --inline-suppr
    cppcheck: --suppress=*:.pio/libdeps/*
build_flags =
    -D APP_NAME=\"nrf52840-supermini\"
    -D APP_VERSION=\"0.1.0\"

[env:supermini]
; Default application target for nRF52840 SuperMini / nice!nano.
